Repository 98OO/colla-frontend, pull requests merged in 2024-11, with the labels that each got.

#142 팀스페이스의 읽지 않은 전체 채팅 개수 제공
  src/App.tsx
  src/components/Chat/ChatRoom/ChatRoom.styled.ts
  src/components/Chat/ChatRoom/ChatRoomCreationModal/ChatRoomCreationModal.tsx
  src/components/Chat/Chatting/Chatting.tsx
  src/components/Chat/MyMessageBox/MyMessageBox.styled.ts
  src/components/Chat/OtherMessageBox/OtherMessageBox.styled.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/GNB/GNBMenu/GNBTeamSpace/GNBTeamSpace.tsx
  src/components/common/SideNavigationBar/SNBFull/SNBFull.tsx
  src/components/common/SideNavigationBar/SNBIcon/SNBIcon.tsx
  src/hooks/queries/chat/useCreateChatChannelMutation.tsx
  src/hooks/queries/teamspace/useRecordTeamSpace.ts
  src/hooks/queries/useLoginMutation.tsx
  src/hooks/queries/useOauthLoginMutation.tsx
  src/stores/socketStore.ts
  src/types/user.ts
Labels: 🔨 Refactor

#146 main 브랜치 병합
  src/components/Chat/Chatting/Chatting.styled.ts
  src/components/Chat/Chatting/Chatting.tsx
  src/components/Chat/MyMessageBox/MyMessageBox.styled.ts
  src/components/Chat/MyMessageBox/MyMessageBox.tsx
  src/components/Chat/OtherMessageBox/OtherMessageBox.styled.ts
  src/components/Chat/OtherMessageBox/OtherMessageBox.tsx
Labels: 🌿 merge

#151 일반 피드 작성을 위한 에디터 구현 및 피드 리팩토링
  package-lock.json
  package.json
  src/App.tsx
  src/apis/post/postNormalFeed.ts
  src/assets/svg/alignCenter.svg
  src/assets/svg/alignLeft.svg
  src/assets/svg/alignRight.svg
  src/assets/svg/blockQuote.svg
  src/assets/svg/bold.svg
  src/assets/svg/bulletList.svg
  src/assets/svg/chevrons-right.svg
  src/assets/svg/code.svg
  src/assets/svg/heading-one.svg
  src/assets/svg/heading-three.svg
  src/assets/svg/heading-two.svg
  src/assets/svg/index.ts
  src/assets/svg/italic.svg
  src/assets/svg/orderedList.svg
  src/assets/svg/strike.svg
  src/assets/svg/underLine.svg
  src/assets/svg/x.svg
  src/components/Feed/Detail/Normal/NormalDetail.styled.ts
  src/components/Feed/Detail/Normal/NormalDetail.tsx
  src/components/Feed/Feed.styled.ts
  src/components/Feed/Feed.tsx
  src/components/Post/Editor/Editor.styled.ts
  src/components/Post/Editor/Editor.tsx
  src/components/Post/EditorMenu/EditorMenu.styled.ts
  src/components/Post/EditorMenu/EditorMenu.tsx
  src/components/Post/EditorMenuButton/EditorMenuButton.styled.ts
  src/components/Post/EditorMenuButton/EditorMenuButton.tsx
  src/components/Post/EditorMenuButton/getButtons.ts
  src/components/Post/LNB/LNB.styled.ts
  src/components/Post/LNB/LNB.tsx
  src/components/Post/NormalPost/NormalPost.styled.ts
  src/components/Post/NormalPost/NormalPost.tsx
  src/components/common/Drawer/Drawer.styled.ts
  src/components/common/Drawer/Drawer.tsx
  src/components/common/FileUploadBox/FileUploadBox.styled.ts
  src/components/common/FileUploadBox/FileUploadBox.tsx
  src/constants/api.ts
  src/constants/feed.ts
  src/constants/post.ts
  src/hooks/common/useMeasureWidth.ts
  src/hooks/post/useFeedDrawer.ts
  src/hooks/post/usePostEditor.ts
  src/hooks/queries/post/useNormalFeedMutation.tsx
  src/pages/FeedPage/FeedPage.styled.ts
  src/pages/FeedPage/FeedPage.tsx
  src/pages/PostPage/PostPage.tsx
  src/styles/GlobalStyle.ts
  src/styles/editorStyles.ts
  src/styles/layout.ts
  src/types/feed.ts
  src/utils/editorImageUtils.ts
  src/utils/getSanitizedFeeds.ts
Labels: ✨ Feature

#149 채팅 디자인 및 사용성 개선
  src/components/Chat/ChatAttachment/ChatAttachments.styled.tsx
  src/components/Chat/ChatAttachment/ChatAttachments.tsx
  src/components/Chat/ChatRoom/ChatRoom.styled.ts
  src/components/Chat/ChatRoom/ChatRoom.tsx
  src/components/Chat/ChatRoom/ChatRoomCreationModal/ChatRoomCreationModal.styled.ts
  src/components/Chat/ChatRoom/ChatRoomCreationModal/ChatRoomCreationModal.tsx
  src/components/Chat/Chatting/Chatting.styled.ts
  src/components/Chat/Chatting/Chatting.tsx
  src/components/Chat/LatestMessageBox/LatestMessageBox.styled.ts
  src/components/Chat/MyMessageBox/MyMessageBox.styled.ts
  src/components/Chat/MyMessageBox/MyMessageBox.tsx
  src/components/Chat/OtherMessageBox/OtherMessageBox.styled.ts
  src/components/Chat/OtherMessageBox/OtherMessageBox.tsx
  src/components/common/Avatar/Avatar.styled.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/IconButton/IconButton.styled.ts
  src/components/common/Profile/Profile.styled.ts
  src/components/common/Profile/Profile.tsx
  src/pages/ChatPage/ChatPage.styled.ts
  src/pages/ChatPage/ChatPage.tsx
  src/styles/layout.ts
  src/styles/tokens/units.ts
Labels: 🔨 Refactor, ✨ Feature

#153 미구현 UI 요소 숨김 처리 및 기타 UI 변경
  src/components/common/Button/Button.styled.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/SideNavigationBar/FeedMenu/FeedMenu.tsx
  src/components/common/SideNavigationBar/FeedMenuItem/FeedMenuItem.tsx
  src/components/common/SideNavigationBar/SNBFull/SNBFull.tsx
  src/components/common/SideNavigationBar/SNBIcon/SNBIcon.tsx
  src/pages/MyPage/MyPage.tsx
  src/types/feed.ts
Labels: 🔨 Refactor

#156 자료 저장소 페이지 리팩토링
  src/assets/svg/PDFLogo.svg
  src/assets/svg/chevron-left.svg
  src/assets/svg/chevron-right.svg
  src/assets/svg/chevrons-left.svg
  src/assets/svg/index.ts
  src/components/Document/DocumentItem/DocumentItem.styled.ts
  src/components/Document/DocumentItem/DocumentItem.tsx
  src/hooks/queries/document/useDocumentQuery.ts
  src/pages/DocumentPage/DocumentPage.styled.ts
  src/pages/DocumentPage/DocumentPage.tsx
  src/types/document.ts
  src/utils/getFormattedDate.ts
Labels: 🔨 Refactor

#160 피드 상세 페이지 댓글 작성 구현
  src/apis/Feed/Comment/deleteComment.ts
  src/apis/Feed/Comment/patchComment.ts
  src/apis/Feed/Comment/postComment.ts
  src/components/Feed/CommentInput/CommentInput.styled.ts
  src/components/Feed/CommentInput/CommentInput.tsx
  src/components/Feed/Detail/Normal/NormalDetail.tsx
  src/constants/api.ts
  src/hooks/queries/Feed/Comment/useDeleteCommentMutation.ts
  src/hooks/queries/Feed/Comment/useLeaveCommentMutation.ts
  src/hooks/queries/Feed/Comment/usePatchCommentMutation.ts
  src/types/feed.ts
Labels: ✨ Feature

#159 main 브랜치 병합
  src/apis/Feed/Comment/deleteComment.ts
  src/apis/Feed/Comment/patchComment.ts
  src/apis/Feed/Comment/postComment.ts
  src/assets/svg/PDFLogo.svg
  src/assets/svg/chevron-left.svg
  src/assets/svg/chevron-right.svg
  src/assets/svg/chevrons-left.svg
  src/assets/svg/index.ts
  src/components/Document/DocumentItem/DocumentItem.styled.ts
  src/components/Document/DocumentItem/DocumentItem.tsx
  src/components/Feed/CommentInput/CommentInput.styled.ts
  src/components/Feed/CommentInput/CommentInput.tsx
  src/components/Feed/Detail/Normal/NormalDetail.tsx
  src/components/common/Button/Button.styled.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/SideNavigationBar/FeedMenu/FeedMenu.tsx
  src/components/common/SideNavigationBar/FeedMenuItem/FeedMenuItem.tsx
  src/components/common/SideNavigationBar/SNBFull/SNBFull.tsx
  src/components/common/SideNavigationBar/SNBIcon/SNBIcon.tsx
  src/constants/api.ts
  src/hooks/queries/Feed/Comment/useDeleteCommentMutation.ts
  src/hooks/queries/Feed/Comment/useLeaveCommentMutation.ts
  src/hooks/queries/Feed/Comment/usePatchCommentMutation.ts
  src/hooks/queries/document/useDocumentQuery.ts
  src/pages/DocumentPage/DocumentPage.styled.ts
  src/pages/DocumentPage/DocumentPage.tsx
  src/pages/MyPage/MyPage.tsx
  src/types/document.ts
  src/types/feed.ts
  src/utils/getFormattedDate.ts
Labels: 🌿 merge

#163 main 브랜치 병합
  src/components/common/GNB/GNB.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 🌿 merge

#164 일반 피드 작성 및 피드 조회 기능 리펙터링
  src/assets/svg/attachment.svg
  src/assets/svg/comment.svg
  src/assets/svg/index.ts
  src/components/Feed/Detail/Normal/NormalDetail.styled.ts
  src/components/Feed/Detail/Normal/NormalDetail.tsx
  src/components/Feed/Feed.styled.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedAuthors/FeedAuthor.styled.ts
  src/components/Feed/FeedAuthors/FeedAuthor.tsx
  src/components/common/Avatar/Avatar.styled.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Input/Input.styled.ts
  src/pages/FeedPage/FeedPage.styled.ts
  src/styles/editorStyles.ts
  src/utils/getFormattedDate.ts
Labels: ✨ Feature

#165 main 브랜치 병합
  src/assets/svg/attachment.svg
  src/assets/svg/comment.svg
  src/assets/svg/index.ts
  src/components/Feed/Detail/Normal/NormalDetail.styled.ts
  src/components/Feed/Detail/Normal/NormalDetail.tsx
  src/components/Feed/Feed.styled.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedAuthors/FeedAuthor.styled.ts
  src/components/Feed/FeedAuthors/FeedAuthor.tsx
  src/components/common/Avatar/Avatar.styled.ts
  src/components/common/Avatar/Avatar.tsx
  src/components/common/Input/Input.styled.ts
  src/pages/FeedPage/FeedPage.styled.ts
  src/styles/editorStyles.ts
  src/utils/getFormattedDate.ts
Labels: 🌿 merge

#172 자료 수집 피드 컴포넌트 이름 수정
  src/components/Feed/CollectFeed/Collect.styled.ts
  src/components/Feed/CollectFeed/Collect.tsx
  src/pages/FeedPage/FeedPage.tsx
Labels: 🐛 Bug

#173 main 브랜치 병합
  src/apis/teamspace/getTeamSpaceInformation.ts
  src/assets/svg/clock.svg
  src/assets/svg/index.ts
  src/components/Chat/ChatRoom/ChatRoomCreationModal/ChatRoomCreationModal.tsx
  src/components/Feed/Attachments/Attachments.tsx
  src/components/Feed/CollectFeed/Collect.styled.ts
  src/components/Feed/CollectFeed/Collect.tsx
  src/components/Feed/CollectFeed/SubTask/SubTask.styled.ts
  src/components/Feed/CollectFeed/SubTask/SubTask.tsx
  src/components/Feed/CommentInput/CommentInput.tsx
  src/components/Feed/Comments/Comment.styled.ts
  src/components/Feed/Comments/Comment.tsx
  src/components/Feed/Detail/Collect/CollectDetail.styled.ts
  src/components/Feed/Detail/Collect/CollectDetail.tsx
  src/components/Feed/Detail/Normal/NormalDetail.styled.ts
  src/components/Feed/Detail/Normal/NormalDetail.tsx
  src/components/Feed/ProgressChip/ProgressChip.styled.ts
  src/components/Feed/ProgressChip/ProgressChip.tsx
  src/components/Post/Editor/Editor.styled.ts
  src/components/Post/Editor/Editor.tsx
  src/components/Post/NormalPost/NormalPost.styled.ts
  src/components/Post/NormalPost/NormalPost.tsx
  src/components/common/Drawer/Drawer.styled.ts
  src/components/common/Drawer/Drawer.tsx
  src/components/common/GNB/GNB.styled.ts
  src/components/common/GNB/GNB.tsx
  src/components/common/GNB/GNBMenu/GNBTeamSpace/GNBTeamSpace.syled.ts
  src/components/common/GNB/GNBMenu/GNBTeamSpace/GNBTeamSpace.tsx
  src/components/common/Input/Input.tsx
  src/components/common/OauthButton/OauthButton.styled.ts
  src/components/common/Profile/Profile.tsx
  src/components/common/Toast/Toast.styled.ts
  src/components/common/Toast/Toast.tsx
  src/components/common/ToastContainer/ToastContainer.styled.ts
  src/hooks/queries/useLoginMutation.tsx
  src/hooks/queries/useOauthLoginMutation.tsx
  src/hooks/queries/useParticipateTeamSpaceMutation.ts
  src/pages/FeedPage/FeedPage.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/SignInPage/SignInPage.styled.ts
  src/pages/SignInPage/SignInPage.tsx
  src/styles/GlobalStyle.ts
  src/types/feed.ts
  src/utils/getFormattedDate.ts
Labels: 🌿 merge

#177 자료 수집 피드 작성 페이지 구현
  src/apis/post/postCollectFeed.ts
  src/components/Feed/Detail/Collect/CollectDetail.styled.ts
  src/components/Post/CollectPost/CollectPost.styled.ts
  src/components/Post/CollectPost/CollectPost.tsx
  src/constants/api.ts
  src/hooks/post/usePostEditor.ts
  src/hooks/queries/post/useCollectFeedMutation.ts
  src/pages/PostPage/PostPage.tsx
  src/types/feed.ts
Labels: ✨ Feature

#178 main 브랜치 병합
  package-lock.json
  package.json
  src/apis/Feed/Collect/getCollectSubTask.ts
  src/apis/Feed/Collect/patchCollectSubTask.ts
  src/apis/post/postCollectFeed.ts
  src/apis/post/postSchedulingFeed.ts
  src/assets/svg/clock.svg
  src/components/Feed/Detail/Collect/CollectDetail.styled.ts
  src/components/Feed/Detail/Collect/CollectDetail.tsx
  src/components/Feed/Detail/SubTask/SubTaskDetail.styled.ts
  src/components/Feed/Detail/SubTask/SubTaskDetail.tsx
  src/components/Post/Calendar/Calendar.styled.ts
  src/components/Post/Calendar/Calendar.tsx
  src/components/Post/CollectPost/CollectPost.styled.ts
  src/components/Post/CollectPost/CollectPost.tsx
  src/components/Post/DatePicker/DatePicker.styled.ts
  src/components/Post/DatePicker/DatePicker.tsx
  src/components/Post/SchedulingPost/SchedulingPost.styled.ts
  src/components/Post/SchedulingPost/SchedulingPost.tsx
  src/components/Post/SchedulingPost/Step/SelectDateStep.tsx
  src/components/Post/SchedulingPost/Step/SetTimeStep.tsx
  src/components/common/IconButton/IconButton.styled.ts
  src/components/common/IconButton/IconButton.tsx
  src/components/common/Select/Select.styled.ts
  src/components/common/ToastContainer/ToastContainer.styled.ts
  src/constants/api.ts
  src/constants/post.ts
  src/hooks/post/useCalendar.ts
  src/hooks/post/useDaySelection.ts
  src/hooks/post/usePostEditor.ts
  src/hooks/queries/Feed/Collect/useCollectSubTaskMutation.ts
  src/hooks/queries/Feed/Collect/useCollectSubTaskQuery.ts
  src/hooks/queries/post/useCollectFeedMutation.ts
  src/hooks/queries/post/useSchedulingFeedMutation.tsx
  src/pages/PostPage/PostPage.tsx
  src/types/feed.ts
  src/types/post.ts
  src/utils/getParsedTime.ts
Labels: 🌿 merge

#179 GNB 리팩토링
  src/components/common/GNB/GNB.tsx
  src/components/common/GNB/GNBMenu/GNBTeamInfo/GNBTeamInfo.tsx
  src/components/common/GNB/GNBMenu/GNBTeamSpace/GNBTeamSpace.tsx
  src/hooks/queries/teamspace/useRecordTeamSpace.ts
Labels: 🔨 Refactor

#180 main 브랜치 병합
  src/components/common/GNB/GNB.tsx
  src/components/common/GNB/GNBMenu/GNBTeamInfo/GNBTeamInfo.tsx
  src/components/common/GNB/GNBMenu/GNBTeamSpace/GNBTeamSpace.tsx
  src/hooks/queries/teamspace/useRecordTeamSpace.ts
Labels: 🌿 merge

#184 재발급된 access token이 정상적으로 반영될 수 있도록 수정
  src/apis/axiosInterceptors.ts
  src/apis/user/getNewToken.ts
  src/types/user.ts
Labels: 🐛 Bug
