Repository 98OO/colla-frontend, pull requests merged in 2024-10, with the labels that each got.

#116 Socket 통신 관련 https 이슈 해결 사항 적용
  src/constants/api.ts
  src/hooks/queries/useLoginMutation.tsx
  src/hooks/queries/useOauthLoginMutation.tsx
  src/pages/SignInPage/SignInPage.tsx
Labels: ✨ Feature

#117 React, Vite 테스트를 위한 라이브러리 설치 및 Config 파일 수정
  package.json
  vite.config.ts
Labels: ✨ Feature

#119 커스텀 훅 common 디렉터리 테스트 코드 작성
  .eslintrc.cjs
  package.json
  setupTests.ts
  src/hooks/common/__tests__/useMenu.test.tsx
  src/hooks/common/__tests__/useOutSideClick.test.tsx
  src/hooks/common/__tests__/useOverlay.test.ts
  vite.config.ts
Labels: ✅ Test

#125 피드 작성을 위한 피드 메뉴 구현
  src/AppRouter.tsx
  src/assets/svg/collect.svg
  src/assets/svg/index.ts
  src/assets/svg/normal.svg
  src/assets/svg/scheduling.svg
  src/assets/svg/vote.svg
  src/components/common/SideNavigationBar/FeedMenu/FeedMenu.styled.ts
  src/components/common/SideNavigationBar/FeedMenu/FeedMenu.tsx
  src/components/common/SideNavigationBar/FeedMenuItem/FeedMenuItem.styled.ts
  src/components/common/SideNavigationBar/FeedMenuItem/FeedMenuItem.tsx
  src/components/common/SideNavigationBar/SNBFull/SNBFull.styled.ts
  src/components/common/SideNavigationBar/SNBFull/SNBFull.tsx
  src/components/common/SideNavigationBar/SNBIcon/SNBIcon.styled.ts
  src/components/common/SideNavigationBar/SNBIcon/SNBIcon.tsx
  src/constants/path.ts
  src/pages/PostPage/PostPage.tsx
  src/styles/layout.ts
  src/types/feed.ts
Labels: ✨ Feature

#130 채팅 1차 리팩토링
  .github/workflows/main.yml
  src/App.tsx
  src/apis/chat/getChatMessage.ts
  src/components/Chat/ChatRoom/ChatRoom.styled.ts
  src/components/Chat/ChatRoom/ChatRoom.tsx
  src/components/Chat/ChatRoom/ChatRoomCreationModal/ChatRoomCreationModal.styled.ts
  src/components/Chat/ChatRoom/ChatRoomCreationModal/ChatRoomCreationModal.tsx
  src/components/Chat/Chatting/Chatting.styled.ts
  src/components/Chat/Chatting/Chatting.tsx
  src/components/Chat/LatestMessageBox/LatestMessageBox.styled.ts
  src/components/Chat/LatestMessageBox/LatestMessageBox.tsx
  src/components/Chat/MyMessageBox/MyMessageBox.styled.ts
  src/components/Chat/MyMessageBox/MyMessageBox.tsx
  src/components/Chat/OtherMessageBox/OtherMessageBox.styled.ts
  src/components/Chat/OtherMessageBox/OtherMessageBox.tsx
  src/components/common/GNB/GNB.tsx
  src/components/common/GNB/GNBMenu/GNBTeamSpace/GNBTeamSpace.tsx
  src/components/common/SideNavigationBar/MenuItem/MenuItem.tsx
  src/components/common/SideNavigationBar/SNBIcon/SNBIcon.tsx
  src/constants/api.ts
  src/constants/size.ts
  src/hooks/queries/chat/useChatMesaageQuery.ts
  src/hooks/queries/useLoginMutation.tsx
  src/pages/ChatPage/ChatPage.styled.ts
  src/pages/ChatPage/ChatPage.tsx
  src/styles/layout.ts
  src/utils/getFormattedDate.ts
Labels: 🔨 Refactor

#138 package-lock.json 동기화
  package-lock.json
Labels: 🐛 Bug
